{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Inserimento dei dati nel database tramite foglio excell\n",
    "### Matter Of Design"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "!pip install pandas openpyxl mysql-connector-python"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 608, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 1936, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 531, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 775, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 446, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\emmal\\AppData\\Local\\Temp\\ipykernel_9344\\409229229.py\", line 2, in <module>\n",
      "    import pandas as pd\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py\", line 39, in <module>\n",
      "    from pandas.compat import (\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\compat\\__init__.py\", line 27, in <module>\n",
      "    from pandas.compat.pyarrow import (\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\compat\\pyarrow.py\", line 8, in <module>\n",
      "    import pyarrow as pa\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.2 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 608, in run_forever\n",
      "    self._run_once()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 1936, in _run_once\n",
      "    handle._run()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 542, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 531, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 775, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 446, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3051, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3106, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3311, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3493, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3553, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\emmal\\AppData\\Local\\Temp\\ipykernel_9344\\409229229.py\", line 2, in <module>\n",
      "    import pandas as pd\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\__init__.py\", line 62, in <module>\n",
      "    from pandas.core.api import (\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\api.py\", line 9, in <module>\n",
      "    from pandas.core.dtypes.dtypes import (\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pandas\\core\\dtypes\\dtypes.py\", line 24, in <module>\n",
      "    from pandas._libs import (\n",
      "  File \"c:\\Users\\emmal\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mThe Kernel crashed while executing code in the current cell or a previous cell. \n",
      "\u001b[1;31mPlease review the code in the cell(s) to identify a possible cause of the failure. \n",
      "\u001b[1;31mClick <a href='https://aka.ms/vscodeJupyterKernelCrash'>here</a> for more info. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "# Librerie necessarie\n",
    "import pandas as pd\n",
    "import mysql.connector"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Caricamento dati"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Caricamento del foglio: PAVIMENTO_LEGNO, ID Tipologia: 1\n"
     ]
    }
   ],
   "source": [
    "# Funzione per connettersi al database\n",
    "def connect_to_db():\n",
    "    try:\n",
    "        connection = mysql.connector.connect(\n",
    "            host='matterofdesign.cboqqic8cvp0.eu-west-2.rds.amazonaws.com',\n",
    "            user='Massaro',\n",
    "            password='4PGZUfbq^$pbngQ',\n",
    "            database='MatterOfDesign'\n",
    "        )\n",
    "        if connection.is_connected():\n",
    "            print(\"Connected to MySQL database\")\n",
    "            return connection\n",
    "    except mysql.connector.Error as e:\n",
    "        print(f\"Error: {e}\")\n",
    "        return None\n",
    "\n",
    "# Funzione aggiornata per caricare i dati\n",
    "def carica_dati(file_path, foglio, tipologia_id):\n",
    "    connection = connect_to_db()\n",
    "    if connection is None:\n",
    "        print(\"Errore nella connessione al database.\")\n",
    "        return\n",
    "\n",
    "    cursor = connection.cursor()\n",
    "\n",
    "    try:\n",
    "        # Leggi il foglio Excel\n",
    "        df = pd.read_excel(file_path, sheet_name=foglio)\n",
    "        df.dropna(how='all', inplace=True)  # Elimina righe completamente vuote\n",
    "\n",
    "        # Verifica la presenza della colonna codice_articolo\n",
    "        if \"codice_articolo\" not in df.columns:\n",
    "            print(f\"Il foglio '{foglio}' non contiene la colonna 'codice_articolo'.\")\n",
    "            return\n",
    "\n",
    "        # Mantieni solo righe con codice_articolo non vuoto\n",
    "        df = df[df[\"codice_articolo\"].notnull()]\n",
    "\n",
    "        if df.empty:\n",
    "            print(f\"Il foglio '{foglio}' non contiene elementi validi. Salto il caricamento.\")\n",
    "            return\n",
    "\n",
    "        # Aggiungi Tipologia_ID\n",
    "        df[\"tipologia_id\"] = tipologia_id\n",
    "\n",
    "        # Lista delle colonne richieste\n",
    "        colonne_richieste = [\n",
    "            \"codice_articolo\", \"brand\", \"finitura\", \"posa\", \"collezione\",\n",
    "            \"dimensione\", \"prezzo_unitario\", \"prezzo_mq\", \"colore\", \"spessore\",\n",
    "            \"documento\", \"immagine\", \"nota\", \"peso\", \"categoria\"\n",
    "        ]\n",
    "\n",
    "        # Aggiungi colonne mancanti con valore None\n",
    "        for colonna in colonne_richieste:\n",
    "            if colonna not in df.columns:\n",
    "                df[colonna] = None\n",
    "\n",
    "        # Converti NaN in None (importante per MySQL)\n",
    "        df = df.where(pd.notnull(df), None)\n",
    "\n",
    "        # Verifica che tutte le colonne siano in formato stringa o compatibile\n",
    "        df = df.astype(object).replace({pd.NA: None})\n",
    "\n",
    "        # Query di controllo per evitare duplicati\n",
    "        check_query = \"SELECT COUNT(*) FROM Prodotto WHERE codice_articolo = %s AND tipologia_id = %s\"\n",
    "\n",
    "        # Query di inserimento\n",
    "        insert_query = \"\"\"\n",
    "        INSERT INTO Prodotto (codice_articolo, brand, finitura, posa, collezione, dimensione,\n",
    "        prezzo_unitario, prezzo_mq, colore, spessore, tipologia_id, documento, immagine, nota,\n",
    "        peso, categoria)\n",
    "        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)\n",
    "        \"\"\"\n",
    "\n",
    "        # Inserisci i dati\n",
    "        for _, row in df.iterrows():\n",
    "            codice_articolo = row[\"codice_articolo\"]\n",
    "\n",
    "            # Verifica se il prodotto esiste già\n",
    "            cursor.execute(check_query, (codice_articolo, tipologia_id))\n",
    "            result = cursor.fetchone()\n",
    "\n",
    "            if result[0] == 0:  # Se il prodotto non esiste già\n",
    "                data = (\n",
    "                    row[\"codice_articolo\"], row[\"brand\"], row[\"finitura\"], row[\"posa\"],\n",
    "                    row[\"collezione\"], row[\"dimensione\"], row[\"prezzo_unitario\"],\n",
    "                    row[\"prezzo_mq\"], row[\"colore\"], row[\"spessore\"], row[\"tipologia_id\"],\n",
    "                    row[\"documento\"], row[\"immagine\"], row[\"nota\"], row[\"peso\"], row[\"categoria\"]\n",
    "                )\n",
    "\n",
    "                # Inserimento nel database\n",
    "                cursor.execute(insert_query, data)\n",
    "                print(f\"Inserito prodotto con codice_articolo: {codice_articolo}\")\n",
    "\n",
    "        # Conferma modifiche\n",
    "        connection.commit()\n",
    "        print(f\"Dati caricati per la tipologia '{foglio}' (ID: {tipologia_id}) con successo!\")\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Errore durante l'elaborazione del foglio '{foglio}': {e}\")\n",
    "\n",
    "    finally:\n",
    "        cursor.close()\n",
    "        connection.close()\n",
    "\n",
    "\n",
    "\n",
    "# Percorso del file Excel\n",
    "file_path = r\"C:/Users/emmal/Desktop/STAGE/PROGETTO/HowToDo/Listino.xlsx\"\n",
    "\n",
    "# Dizionario foglio-tipologia\n",
    "foglio_to_tipologia_id = {\n",
    "    \"PAVIMENTO_LEGNO\": 1,\n",
    "    \"PAVIMENTO\": 2,\n",
    "    \"RIVESTIMENTI\": 3,\n",
    "    \"SANITARI\": 4,\n",
    "    \"RUBINETTERIA\": 5,\n",
    "    \"VASCHE_BAGNO\": 6,\n",
    "    \"PIATTI_DOCCIA\": 7,\n",
    "    \"PORTE_INTERNE\": 8,\n",
    "    \"TERMOARREDI\": 9,\n",
    "    \"WELLNESS\": 10,\n",
    "    \"LAVABI\": 11,\n",
    "}\n",
    "\n",
    "# Caricamento fogli\n",
    "for foglio, tipologia_id in foglio_to_tipologia_id.items():\n",
    "    print(f\"Caricamento del foglio: {foglio}, ID Tipologia: {tipologia_id}\")\n",
    "    carica_dati(file_path, foglio, tipologia_id)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Verifica dati"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def fetch_data():\n",
    "    connection = connect_to_db()\n",
    "    if connection is None:\n",
    "        print(\"Errore nella connessione al database.\")\n",
    "        return\n",
    "\n",
    "    cursor = connection.cursor()\n",
    "\n",
    "    try:\n",
    "        cursor.execute(\"SELECT * FROM Prodotto\")\n",
    "        results = cursor.fetchall()\n",
    "\n",
    "        if not results:\n",
    "            print(\"La tabella 'Prodotto' è vuota o non ci sono dati.\")\n",
    "            return\n",
    "\n",
    "        # Ottieni i nomi delle colonne\n",
    "        column_names = [desc[0] for desc in cursor.description]\n",
    "        print(\"Dati nella tabella 'Prodotto':\")\n",
    "        print(\"-\" * 160)  # Larghezza adattata per tutte le colonne\n",
    "        print(\" | \".join(f\"{col:<15}\" for col in column_names))\n",
    "        print(\"-\" * 160)\n",
    "\n",
    "        for row in results:\n",
    "            # Sostituisci valori None con \"N/A\" per evitare errori di formattazione\n",
    "            formatted_row = [value if value is not None else \"N/A\" for value in row]\n",
    "            print(\" | \".join(f\"{str(col):<15}\" for col in formatted_row))\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Errore durante il recupero dei dati: {e}\")\n",
    "    finally:\n",
    "        cursor.close()\n",
    "        connection.close()\n",
    "\n",
    "\n",
    "# Esegui la funzione per vedere i dati\n",
    "fetch_data()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
